/* global __dirname */

var commonCases = require('./common-cases');
var runCommonCase = require('./run-common-case');

const storeFile = __dirname + '/fixtures/test.json';

var testCases = [
  commonCases.initialStateCase,
  commonCases.moreRecordsCase,
  {
    name: 'Reopening',
    createNewTrackerInTest: true,
    expectedSalientTerms: [
      { term: 'the', count: 4, countsInRefs: { a: 2, b: 2 }, refs: ['a', 'b'] },
      {
        term: 'delightful',
        count: 3,
        countsInRefs: { a: 1, b: 2 },
        refs: ['a', 'b'],
      },
      { term: 'hit', count: 3, countsInRefs: { a: 2, b: 1 }, refs: ['a', 'b'] },
      {
        term: 'blaster',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      { term: 'it', count: 2, countsInRefs: { a: 1, b: 1 }, refs: ['a', 'b'] },
      {
        term: 'like',
        count: 2,
        countsInRefs: { b: 1, c: 1 },
        refs: ['b', 'c'],
      },
      { term: 'good', count: 2, countsInRefs: { b: 2 }, refs: ['b'] },
      { term: 'really', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
      { term: 'state', count: 2, countsInRefs: { b: 2 }, refs: ['b'] },
      { term: 'know', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
      { term: 'though', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
      { term: 'look', count: 2, countsInRefs: { b: 2 }, refs: ['b'] },
      { term: 'guy', count: 2, countsInRefs: { a: 1, b: 1 }, refs: ['a', 'b'] },
      {
        term: 'even',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      { term: 'br', count: 2, countsInRefs: { c: 2 }, refs: ['c'] },
      { term: 'cheerful', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
      { term: 'liked', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
      {
        term: 'kero',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      { term: 'and', count: 2, countsInRefs: { b: 2 }, refs: ['b'] },
      {
        term: 'level',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      {
        term: 'music',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      {
        term: 'game',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
    ],
    expectedTerms: {
      cells: { term: 'cells', count: 1, countsInRefs: { a: 1 }, refs: ['a'] },
      game: {
        term: 'game',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      blaster: {
        term: 'blaster',
        count: 2,
        countsInRefs: { a: 1, b: 1 },
        refs: ['a', 'b'],
      },
      symphony: {
        term: 'symphony',
        count: 1,
        countsInRefs: { c: 1 },
        refs: ['c'],
      },
    },
    expectedDocs: {
      a: {
        id: 'a',
        termCount: 71,
        countsPerTerm: {
          hey: 1,
          liked: 2,
          dead: 1,
          cells: 1,
          limited: 1,
          video: 1,
          game: 1,
          time: 1,
          dad: 1,
          it: 1,
          indeed: 1,
          metroidvania: 1,
          format: 1,
          love: 1,
          procedurally: 1,
          generation: 1,
          freed: 1,
          thinking: 1,
          inspect: 1,
          every: 1,
          last: 1,
          corner: 1,
          plus: 1,
          really: 2,
          enjoyed: 1,
          finding: 1,
          healing: 1,
          meats: 1,
          think: 1,
          kero: 1,
          blaster: 1,
          even: 1,
          though: 2,
          tried: 1,
          ios: 1,
          actiony: 1,
          touch: 1,
          controls: 1,
          on: 1,
          switch: 1,
          feels: 1,
          great: 1,
          fine: 1,
          details: 1,
          delightful: 1,
          the: 2,
          little: 1,
          guy: 1,
          blinking: 1,
          hit: 2,
          button: 1,
          start: 1,
          level: 1,
          monsters: 1,
          faces: 1,
          music: 1,
          cheerful: 2,
          effective: 1,
          smb2: 1,
          way: 1,
          first: 1,
          know: 2,
          going: 1,
          mean: 1,
        },
      },
      b: {
        id: 'b',
        termCount: 56,
        countsPerTerm: {
          kero: 1,
          blaster: 1,
          good: 2,
          feeling: 1,
          game: 1,
          it: 1,
          mostly: 1,
          shading: 1,
          pixel: 1,
          art: 1,
          no: 1,
          implying: 1,
          '3d': 1,
          even: 1,
          level: 1,
          nes: 1,
          games: 1,
          all: 1,
          flat: 1,
          almost: 1,
          like: 1,
          atari: 1,
          iconography: 1,
          delightful: 2,
          and: 2,
          second: 1,
          state: 2,
          two: 1,
          sprites: 1,
          hits: 1,
          spot: 1,
          the: 2,
          shocked: 1,
          look: 2,
          guys: 1,
          hit: 1,
          adorbs: 1,
          main: 1,
          guy: 1,
          face: 1,
          gets: 1,
          item: 1,
          also: 1,
          music: 1,
          calmly: 1,
          happy: 1,
          anyway: 1,
          worth: 1,
          playing: 1,
          feel: 1,
        },
      },
      c: {
        id: 'c',
        termCount: 21,
        countsPerTerm: {
          href: 1,
          https: 1,
          open: 1,
          spotify: 1,
          com: 1,
          track: 1,
          '6yw4li4vwr4gc8gwkod7t7': 1,
          si: 1,
          '3iocvpfwq5kt2bly3tdjeg': 1,
          speed: 1,
          metal: 1,
          symphony: 1,
          br: 2,
          despite: 1,
          name: 1,
          like: 1,
          guitar: 1,
          virtuosos: 1,
          jamming: 1,
          castlevania: 1,
        },
      },
    },
  },
];

testCases.forEach((testCase) => runCommonCase(testCase, { storeFile }));
