var initialStateCase = {
  name: 'Initial state',
  createNewTrackerInTest: true,
  expectedSalientTerms: [],
  expectedTerms: {
    cells: undefined,
  },
  textProp: 'caption',
  docsToAdd: [
    {
      id: 'a',
      caption: `Hey, I liked Dead Cells. I'm a limited-video-game-time dad. It is indeed a Metroidvania, a format that I love, but the procedurally generation freed me from thinking I had to inspect every last corner. Plus, I really enjoyed finding healing meats again.

I think I liked Kero Blaster even more, though. I had tried it on iOS before, but it's just too actiony for touch controls. On Switch, it feels great, and all the fine details are delightful. The little guy blinking when you hit the button to start the level, monsters faces when their hit. The music is really cheerful in that effective SMB2 way, though at first you don't know it's going to be cheerful, if you know what I mean.`,
    },
  ],
};

var moreRecordsCase = {
  name: 'Add more records',
  createNewTrackerInTest: true,
  expectedSalientTerms: [
    { term: 'really', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
    { term: 'liked', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
    { term: 'the', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
    { term: 'hit', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
    { term: 'cheerful', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
    { term: 'know', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
    { term: 'though', count: 2, countsInRefs: { a: 2 }, refs: ['a'] },
  ],
  expectedTerms: {
    cells: { term: 'cells', count: 1, countsInRefs: { a: 1 }, refs: ['a'] },
    game: { term: 'game', count: 1, countsInRefs: { a: 1 }, refs: ['a'] },
  },
  expectedDocs: {
    a: {
      id: 'a',
      termCount: 71,
      countsPerTerm: {
        hey: 1,
        liked: 2,
        dead: 1,
        cells: 1,
        limited: 1,
        video: 1,
        game: 1,
        time: 1,
        dad: 1,
        it: 1,
        indeed: 1,
        metroidvania: 1,
        format: 1,
        love: 1,
        procedurally: 1,
        generation: 1,
        freed: 1,
        thinking: 1,
        inspect: 1,
        every: 1,
        last: 1,
        corner: 1,
        plus: 1,
        really: 2,
        enjoyed: 1,
        finding: 1,
        healing: 1,
        meats: 1,
        think: 1,
        kero: 1,
        blaster: 1,
        even: 1,
        though: 2,
        tried: 1,
        ios: 1,
        actiony: 1,
        touch: 1,
        controls: 1,
        on: 1,
        switch: 1,
        feels: 1,
        great: 1,
        fine: 1,
        details: 1,
        delightful: 1,
        the: 2,
        little: 1,
        guy: 1,
        blinking: 1,
        hit: 2,
        button: 1,
        start: 1,
        level: 1,
        monsters: 1,
        faces: 1,
        music: 1,
        cheerful: 2,
        effective: 1,
        smb2: 1,
        way: 1,
        first: 1,
        know: 2,
        going: 1,
        mean: 1,
      },
    },
  },
  docsToAdd: [
    {
      id: 'b',
      text: `Kero Blaster is just such a good-feeling game. It's mostly no-shading pixel art. No implying 3D, even at the level NES games did. All flat, almost like Atari, but the iconography is just so delightful. And the second state of those two-state sprites hits the spot. The shocked look of guys when they've been hit is adorbs. The look on the main guy's face when he gets an item: also delightful! And the music is so calmly happy.

Anyway, worth playing to feel good!`,
    },
    {
      id: 'c',
      text: '<a href="https://open.spotify.com/track/6YW4Li4VWR4gc8gwKOd7t7?si=3IOCvPfwQ5KT2BLy3tDjeg">Speed Metal Symphony</a><br><br>Despite the name, it\'s more like guitar virtuosos jamming on some Castlevania.',
    },
  ],
};

module.exports = { initialStateCase, moreRecordsCase };
